
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chizi
 */
public class ticketingHome extends javax.swing.JFrame {

    /**
     * Creates new form ticketingHome
     */
    env env = new env();
    public String ticketer;
    public int orderNo, totalPrice;
    public ticketingHome(String name) {
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton8.setVisible(false);
        jLabel2.setVisible(false);
        jLabel18.setVisible(false);
        jLabel22.setVisible(false);
        jTextArea1.setVisible(false);
        jTextArea2.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane4.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        ticketer = name;
        jLabel3.setText("Ticketed by: " + name);
        refreshMenu();
        DefaultTableModel tm2 = (DefaultTableModel) jTable2.getModel();
        for (int rowNo=0; rowNo<jTable2.getRowCount(); rowNo++){
            totalPrice = totalPrice + Integer.parseInt(tm2.getValueAt(rowNo, 2).toString());
        }
        jLabel24.setText(Integer.toString(totalPrice));
        totalPrice = 0;
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(68, 41, 19));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 470));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 209, 194));
        jLabel1.setText("TICKETING DEPARTMENT");

        jTable1.setBackground(new java.awt.Color(226, 209, 194));
        jTable1.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MENU ITEM", "AVAILABLE PORTIONS", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(226, 209, 194));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(93, 64, 55));
        jButton2.setText("Add Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(226, 209, 194));
        jLabel18.setText("Quantity:");

        jTextField13.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N

        jButton4.setBackground(new java.awt.Color(226, 209, 194));
        jButton4.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(93, 64, 55));
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(226, 209, 194));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(93, 64, 55));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setBackground(new java.awt.Color(226, 209, 194));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 64, 55));
        jLabel2.setText("QUANTITY LOW");
        jLabel2.setOpaque(true);

        jTable2.setBackground(new java.awt.Color(226, 209, 194));
        jTable2.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "PORTIONS", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton5.setBackground(new java.awt.Color(226, 209, 194));
        jButton5.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(93, 64, 55));
        jButton5.setText("Remove Item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(226, 209, 194));
        jRadioButton1.setText("CASH");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(226, 209, 194));
        jRadioButton2.setText("TRANSFER");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(226, 209, 194));
        jRadioButton3.setText("CARD");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(226, 209, 194));
        jLabel19.setText("Paid With:");

        jButton3.setBackground(new java.awt.Color(226, 209, 194));
        jButton3.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(93, 64, 55));
        jButton3.setText("Place Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 209, 194));
        jLabel3.setText("name");

        jLabel20.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(226, 209, 194));
        jLabel20.setText("MENU");

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(226, 209, 194));
        jLabel21.setText("ORDER");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jButton7.setBackground(new java.awt.Color(226, 209, 194));
        jButton7.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(93, 64, 55));
        jButton7.setText("Edit Quantity");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(226, 209, 194));
        jLabel22.setText("Quantity:");

        jTextField14.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N

        jButton8.setBackground(new java.awt.Color(226, 209, 194));
        jButton8.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(93, 64, 55));
        jButton8.setText("EDIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(226, 209, 194));
        jRadioButton4.setText("OTHERS");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(226, 209, 194));
        jLabel23.setText("TOTAL PRICE:");

        jLabel24.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(226, 209, 194));
        jLabel24.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(284, 284, 284))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel20))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jButton4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(187, 187, 187))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton8)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton5)
                                .addGap(53, 53, 53)
                                .addComponent(jButton7)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel18.setVisible(true);
        jTextField13.setVisible(true);
        jButton4.setVisible(true);
        jButton3.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            DefaultTableModel tm2 = (DefaultTableModel) jTable2.getModel();
            int row = jTable1.getSelectedRow();
            String menuItem = tm.getValueAt(row, 0).toString();
            int Qty = Integer.parseInt(jTextField13.getText());
            int availableQty = Integer.parseInt(tm.getValueAt(row, 1).toString());
            for (int rowNo=0; rowNo<jTable2.getRowCount(); rowNo++){
                if (menuItem.equals(tm2.getValueAt(rowNo, 0).toString())) {
                    JOptionPane.showMessageDialog(rootPane, menuItem + " already exists in your order.");
                    jTextField13.setText(null);
                    return;
                }
            }
            if (Qty <= availableQty) {
                int price = Integer.parseInt(tm.getValueAt(row, 2).toString()) * Qty;
                String qty = Integer.toString(Qty);
                String price1 = Integer.toString(price);
                String data[] = {menuItem, qty, price1};

                tm2.addRow(data); 
                jTextField13.setText(null);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Oops! Not enough " + menuItem + " to add to order.");
                jTextField13.setText(null);
            }  
            jLabel18.setVisible(false);
            jTextField13.setVisible(false);
            jButton4.setVisible(false);
            for (int rowNo=0; rowNo<jTable2.getRowCount(); rowNo++){
                totalPrice = totalPrice + Integer.parseInt(tm2.getValueAt(rowNo, 2).toString());
            }
            jLabel24.setText(Integer.toString(totalPrice));
            totalPrice = 0;            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "Error! Please ensure a row in the menu is selected.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel tm2 = (DefaultTableModel) jTable2.getModel();
        int row = jTable2.getSelectedRow();
        tm2.removeRow(row);
        for (int rowNo=0; rowNo<jTable2.getRowCount(); rowNo++){
            totalPrice = totalPrice + Integer.parseInt(tm2.getValueAt(rowNo, 2).toString());
        }
        jLabel24.setText(Integer.toString(totalPrice));
        totalPrice = 0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jButton3.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int count = jTable2.getRowCount();
            String menuItems[] = new String[count];
            int portionsOrdered[] = new int[count];
            int updatedAvailablePortions[] = new int[count];
            String paymentMethod = null;
            Date orderDate = new Date(System.currentTimeMillis());
            DefaultTableModel tm2 = (DefaultTableModel) jTable2.getModel();
            for (int rowNo=0; rowNo<jTable2.getRowCount(); rowNo++){
                totalPrice = totalPrice + Integer.parseInt(tm2.getValueAt(rowNo, 2).toString());
            }
            if (jRadioButton1.isSelected()){
                paymentMethod = "Cash";
            } else if (jRadioButton2.isSelected()){
                paymentMethod = "Card";
            } else if (jRadioButton3.isSelected()){
                paymentMethod = "Transfer";
            } else if (jRadioButton4.isSelected()){
                paymentMethod = "Others";
            }   
            for (int rowNo=0; rowNo<jTable2.getRowCount(); rowNo++){
                menuItems[rowNo] = tm2.getValueAt(rowNo, 0).toString();
                portionsOrdered[rowNo] = Integer.parseInt(tm2.getValueAt(rowNo, 1).toString());
            }            
            Class.forName("com.mysql.cj.jdbc.Driver"); //Connecting and Inserting into db
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteriamanagement", "root", env.Password);
            System.out.println("connected");
            
            if (totalPrice == 0) {
                JOptionPane.showMessageDialog(rootPane, "Cannot make an empty order");
            } else {
                PreparedStatement ps = con.prepareStatement("insert into orders (total_price, payment_method, status, order_date, ticket_by) values (?,?,?,?,?)");
                ps.setInt(1, totalPrice);
                ps.setString(2, paymentMethod);
                ps.setString(3, "Not Served");  
                ps.setDate(4, orderDate);
                ps.setString(5, ticketer);
                int rs = ps.executeUpdate();

                PreparedStatement ps1 = con.prepareStatement("SELECT LAST_INSERT_ID()");
                ResultSet rs1 = ps1.executeQuery();
                if(rs1.next()){
                    orderNo=rs1.getInt(1);
                }            

                PreparedStatement ps2 = con.prepareStatement("insert into items values (?,?,?,?)");
                for (int row=0; row<jTable2.getRowCount(); row++){
                    for (int col=0; col<jTable2.getColumnCount(); col++){
                        Object value = jTable2.getValueAt(row, col);
                        ps2.setObject(col+1, value);
                    }
                    ps2.setInt(4, orderNo);
                    ps2.executeUpdate();
                }

                //Issue occurs when updating the portions of food left after order
                PreparedStatement ps3 = con.prepareStatement("select * from menu where menu_item = ?");
                for (int index=0; index<menuItems.length; index++){
                    ps3.setString(1, menuItems[index]);
                    ResultSet rs3 = ps3.executeQuery();
                    if(rs3.next()){
                        updatedAvailablePortions[index] = rs3.getInt(2) - portionsOrdered[index];
                    }
                    System.out.println(updatedAvailablePortions[index]);
                }

                PreparedStatement ps4 = con.prepareStatement("update menu set portions_available = ? where menu_item = ?");
                for (int index=0; index<menuItems.length; index++){
                    ps4.setInt(1, updatedAvailablePortions[index]);
                    ps4.setString(2, menuItems[index]);
                    ps4.executeUpdate();
                }

                JOptionPane.showMessageDialog(rootPane, "The Ticket Order NO is: "+ orderNo);
                int confirmDelete = JOptionPane.showConfirmDialog(rootPane, "Do you want to print out the receipt?", "Print Receipt", 0, 3);

                if(confirmDelete == JOptionPane.YES_OPTION){
                    String text = "Order NO: " + orderNo + "\n" + "Ticketing By: " + ticketer + "\n" + "Date: " + orderDate + "\n" + "Status: NOT SERVED\n\nQTY ITEM                      PRICE\n"; 
                    for (int rowNo=0; rowNo<jTable2.getRowCount(); rowNo++){
                        text = text.concat(portionsOrdered[rowNo] + "        " + menuItems[rowNo] + "                    " + jTable2.getValueAt(rowNo, 2) + "\n");
                    }
                    text = text.concat("\nPayment Method: " + paymentMethod + "\nTotal Price: N" + totalPrice + "\n\t\t\t\tPayment Confirmed.");
                    jTextArea2.setText(text);
                    jTextArea2.print();
                    jTextArea2.setText(null);
                }
                refreshMenu();
                tm2.setRowCount(0);
                totalPrice = 0;
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "Error");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jButton3.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jButton3.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jLabel22.setVisible(true);
        jTextField14.setVisible(true);
        jButton8.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            DefaultTableModel tm2 = (DefaultTableModel) jTable2.getModel();
            int row = jTable2.getSelectedRow(); 
            String menuItem = tm2.getValueAt(row, 0).toString();
            int Qty = Integer.parseInt(jTextField14.getText());
            for (int rowNo=0; rowNo<jTable1.getRowCount(); rowNo++){
                if (menuItem.equals(tm.getValueAt(rowNo, 0).toString())) {
                    int availableQty = Integer.parseInt(tm.getValueAt(rowNo, 1).toString());
                    int pricePerPortion = Integer.parseInt(tm.getValueAt(rowNo, 2).toString());
                    if (Qty <= availableQty) {
                        Object Qty1 = Integer.valueOf(jTextField14.getText());
                        tm2.setValueAt(Qty1, row, 1);   
                        int price = Qty * pricePerPortion;
                        tm2.setValueAt(price, row, 2);  
                        jTextField14.setText(null);
                    } else {
                       JOptionPane.showMessageDialog(rootPane, "Oops! Not enough " + menuItem + " to add to order.");
                       jTextField14.setText(null);
                    }
                }
            }
            jLabel22.setVisible(false);
            jTextField14.setVisible(false);
            jButton8.setVisible(false);
            for (int rowNo=0; rowNo<jTable2.getRowCount(); rowNo++){
                totalPrice = totalPrice + Integer.parseInt(tm2.getValueAt(rowNo, 2).toString());
            }
            jLabel24.setText(Integer.toString(totalPrice));
            totalPrice = 0;
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "Error! Please ensure a row in the order table is selected.");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        jButton3.setVisible(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    
    private void refreshMenu() {
        try{
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.setRowCount(0);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafeteriamanagement", "root", env.Password);
            System.out.println("connected");
            PreparedStatement ps = con.prepareStatement("select * from menu");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String menuItem = rs.getString(1);
                int portionsAvailable1 = rs.getInt(2);
                int price1 = rs.getInt(3);
                
                String price = String.valueOf(price1);
                String portionsAvailable = String.valueOf(portionsAvailable1);
                String[] row = {menuItem, portionsAvailable, price};
                tm.addRow(row);
            }
            jTable1.setModel(tm);
        }
        catch(Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "Unable to read from DB.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String name;
            public void run() {
                new ticketingHome(name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    // End of variables declaration//GEN-END:variables
}
