
import java.awt.Color;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chizi
 */
public class wordled extends javax.swing.JFrame {
    
    String[][] words = {
        {"Abundant", "Existing or available in large quantities"},
        {"Benevolent", "Kind and generous"},
        {"Catalyst", "Something that causes change or action"},
        {"Divergent", "Moving or extending in different directions"},
        {"Ephemeral", "Lasting for a very short time"},
        {"Facetious", "Treating serious issues with inappropriate humor"},
        {"Gargantuan", "Enormous or gigantic in size"},
        {"Hapless", "Unlucky or unfortunate"},
        {"Iconoclast", "A person who attacks cherished beliefs or institutions"},
        {"Juxtapose", "To place side by side for comparison"},
        {"Kindle", "To ignite or inspire"},
    };
    
    int index = 0; 
    int score = 0;
    int point = 10;
    int trials = 2;
    int reveals = 5;  
    int wordCount = words.length;
    int count = 0;

    /**
     * Creates new form wordledgame
     */
    public wordled() {
        initComponents();
        String word = scrambleWord(words[index][0]).toLowerCase();
        jLabel5.setText(word); 
        
        jLabel8.setText(String.valueOf(score));      
        jLabel12.setText(String.valueOf(trials+1));
        jLabel13.setText(String.valueOf(reveals));
        jLabel15.setText(String.valueOf(wordCount));
        
        blink b = new blink();
        Thread tt = new Thread(b);
        tt.start();
    }

    public String scrambleWord(String text) {
        char[] letters = text.toCharArray();
        Random random = new Random();
        for (int i = 0; i < letters.length; i++) {
            int j = random.nextInt(letters.length);
            char temp = letters[i];
            letters[i] = letters[j];
            letters[j] = temp;
        }
        return new String(letters);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        guessButton = new javax.swing.JButton();
        hintButton = new javax.swing.JButton();
        reshuffleButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        revealButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(157, 138, 124));

        jLabel1.setFont(new java.awt.Font("Centaur", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 30, 23));
        jLabel1.setText("WORDLED");

        guessButton.setBackground(new java.awt.Color(45, 30, 23));
        guessButton.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        guessButton.setForeground(new java.awt.Color(185, 171, 153));
        guessButton.setText("Guess");
        guessButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guessButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guessButtonMouseExited(evt);
            }
        });
        guessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessButtonActionPerformed(evt);
            }
        });

        hintButton.setBackground(new java.awt.Color(45, 30, 23));
        hintButton.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        hintButton.setForeground(new java.awt.Color(185, 171, 153));
        hintButton.setText("Hint");
        hintButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hintButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hintButtonMouseExited(evt);
            }
        });
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        reshuffleButton.setBackground(new java.awt.Color(45, 30, 23));
        reshuffleButton.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        reshuffleButton.setForeground(new java.awt.Color(185, 171, 153));
        reshuffleButton.setText("Reschuffle");
        reshuffleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reshuffleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reshuffleButtonMouseExited(evt);
            }
        });
        reshuffleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reshuffleButtonActionPerformed(evt);
            }
        });

        nextButton.setBackground(new java.awt.Color(45, 30, 23));
        nextButton.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        nextButton.setForeground(new java.awt.Color(185, 171, 153));
        nextButton.setText("Next");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonMouseExited(evt);
            }
        });
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 30, 23));
        jLabel2.setText("WORD");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 30, 23));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 30, 23));
        jLabel4.setText(" ");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 30, 23));
        jLabel5.setText(" ");

        jTextField1.setBackground(new java.awt.Color(141, 119, 168));
        jTextField1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(45, 30, 23));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 30, 23));
        jLabel7.setText("SCORE:");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("0  ");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 30, 23));
        jLabel11.setText("Attempts Left:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText("0  ");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText("0  ");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(45, 30, 23));
        jLabel14.setText("Reveals Left:");

        revealButton.setBackground(new java.awt.Color(45, 30, 23));
        revealButton.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        revealButton.setForeground(new java.awt.Color(185, 171, 153));
        revealButton.setText("Get Letter");
        revealButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                revealButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                revealButtonMouseExited(evt);
            }
        });
        revealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revealButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 30, 23));
        jLabel9.setText("GUESS");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText("20");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setText("WORDS LEFT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(reshuffleButton)
                                .addGap(98, 98, 98)
                                .addComponent(revealButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hintButton)
                                .addGap(137, 137, 137)
                                .addComponent(guessButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(111, 111, 111)
                                .addComponent(jLabel7))
                            .addComponent(nextButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel14))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hintButton)
                    .addComponent(nextButton)
                    .addComponent(guessButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reshuffleButton)
                    .addComponent(revealButton))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guessButtonMouseEntered
        guessButton.setForeground(new Color(45, 30, 23));
        guessButton.setBackground(new Color(185, 171, 153));
    }//GEN-LAST:event_guessButtonMouseEntered

    private void guessButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guessButtonMouseExited
        guessButton.setForeground(new Color(185, 171, 153));
        guessButton.setBackground(new Color(45, 30, 23));
    }//GEN-LAST:event_guessButtonMouseExited

    private void guessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessButtonActionPerformed
        String guess = jLabel3.getText().toLowerCase() + jTextField1.getText().toLowerCase();
        if (wordCount == 0) {
            jLabel12.setText("0");
            jLabel13.setText("0");
            jTextField1.setText("");
            JOptionPane.showMessageDialog(rootPane, "You have reached the end of the game!"); 
        }
        else{
            try {
                if (words[index][0].toLowerCase().equals(guess)){
                    JLabel label = new JLabel("Correct!");
                    label.setForeground(Color.blue);
                    JOptionPane.showMessageDialog(rootPane, label);
                    score = score+point;
                    jLabel8.setText(String.valueOf(score));
                    reveals = reveals + 1;
                    jLabel13.setText(String.valueOf(reveals));
                    nextButtonActionPerformed(evt);
                } else {
                    if (trials == 0) {
                        JOptionPane.showMessageDialog(rootPane, "Trial Limit Exceeded! Too bad!");
                        nextButtonActionPerformed(evt);
                    } else {
                        trials = trials - 1;
                        jLabel12.setText(String.valueOf(trials+1));
                        JLabel label = new JLabel("Incorrect! Try again!");
                        label.setForeground(Color.red);
                        JOptionPane.showMessageDialog(rootPane, label);
                        jTextField1.setText("");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Invalid Entry!");
            }
        }
    }//GEN-LAST:event_guessButtonActionPerformed
  
    private void hintButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hintButtonMouseEntered
        hintButton.setForeground(new Color(45, 30, 23));
        hintButton.setBackground(new Color(185, 171, 153));
    }//GEN-LAST:event_hintButtonMouseEntered

    private void hintButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hintButtonMouseExited
        hintButton.setForeground(new Color(185, 171, 153));
        hintButton.setBackground(new Color(45, 30, 23));
    }//GEN-LAST:event_hintButtonMouseExited

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        if (wordCount == 0) {
            jLabel12.setText("0");
            jLabel13.setText("0");
            jTextField1.setText("");
            JOptionPane.showMessageDialog(rootPane, "You have reached the end of the game!"); 
        }
        else{
            jLabel4.setText(words[index][1]);
        point = 5;
        }        
    }//GEN-LAST:event_hintButtonActionPerformed

    private void reshuffleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reshuffleButtonMouseEntered
        reshuffleButton.setForeground(new Color(45, 30, 23));
        reshuffleButton.setBackground(new Color(185, 171, 153));
    }//GEN-LAST:event_reshuffleButtonMouseEntered

    private void reshuffleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reshuffleButtonMouseExited
        reshuffleButton.setForeground(new Color(185, 171, 153));
        reshuffleButton.setBackground(new Color(45, 30, 23));
    }//GEN-LAST:event_reshuffleButtonMouseExited

    private void reshuffleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reshuffleButtonActionPerformed
        if (wordCount == 0) {
            jLabel12.setText("0");
            jLabel13.setText("0");
            jTextField1.setText("");
            JOptionPane.showMessageDialog(rootPane, "You have reached the end of the game!"); 
        }
        else{
            String word = scrambleWord(words[index][0]).toLowerCase();
            jLabel5.setText(word);
        }        
    }//GEN-LAST:event_reshuffleButtonActionPerformed

    private void nextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseEntered
        nextButton.setForeground(new Color(45, 30, 23));
        nextButton.setBackground(new Color(185, 171, 153));
    }//GEN-LAST:event_nextButtonMouseEntered

    private void nextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseExited
        nextButton.setForeground(new Color(185, 171, 153));
        nextButton.setBackground(new Color(45, 30, 23));
    }//GEN-LAST:event_nextButtonMouseExited

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        jLabel4.setText(" ");
        jLabel3.setText("");
        if (words.length - 1 == index) {
            wordCount = 0;
            jTextField1.setText("");
            jLabel5.setText(" ");            
            jLabel15.setText("0");
            jLabel12.setText("0");
            jLabel13.setText("0");
            JOptionPane.showMessageDialog(rootPane, "You have reached the end of the game!"); 
        } else {
            trials = 2;
            jLabel12.setText(String.valueOf(trials+1));
            count = 0;
            wordCount = wordCount - 1;
            jLabel15.setText(String.valueOf(wordCount));
            point = 10;
            index = index+1;
            String word = scrambleWord(words[index][0]).toLowerCase();
            jLabel5.setText(word);
            jTextField1.setText("");
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void revealButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revealButtonMouseEntered
        revealButton.setForeground(new Color(45, 30, 23));
        revealButton.setBackground(new Color(185, 171, 153));
    }//GEN-LAST:event_revealButtonMouseEntered

    private void revealButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revealButtonMouseExited
        revealButton.setForeground(new Color(185, 171, 153));
        revealButton.setBackground(new Color(45, 30, 23));
    }//GEN-LAST:event_revealButtonMouseExited

    private void revealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revealButtonActionPerformed
        if (wordCount == 0) {
            jLabel12.setText("0");
            jLabel13.setText("0");
            jTextField1.setText("");
            JOptionPane.showMessageDialog(rootPane, "You have reached the end of the game!"); 
        }
        else{
            count = count + 1;
            if (reveals == 0) {
                jLabel13.setText(String.valueOf(reveals));
                JOptionPane.showMessageDialog(rootPane, "Uh Oh! You have used up all your reveals!");
            } else {
                reveals = reveals - 1;
                jLabel13.setText(String.valueOf(reveals));
                jLabel3.setText(words[index][0].substring(0, count).toLowerCase());
            }  
        }
    }//GEN-LAST:event_revealButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wordled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wordled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wordled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wordled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wordled().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guessButton;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton reshuffleButton;
    private javax.swing.JButton revealButton;
    // End of variables declaration//GEN-END:variables
}
